name: C++ CI

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Завантаження коду вашого репозиторію
    - name: Checkout repository
      uses: actions/checkout@v3

  
    - name: Setup compiler
      uses: actions/setup-cpp
      with:
        gcc-version: '11'
    - name: Build with Makefile
      run: |
        make clean
        make
