name: C++ CI

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install -y g++

      - name: Build with Makefile
        run: |
          make clean
          make
