name: Build and Test

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler: g++

      - name: Build project
        run: |
          make
          ls -la

      - name: Test binary
        run: ./main

